twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_5_layout.html.twig',
        '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    ]

when@test:
    twig:
        strict_variables: true
